version: "3.9"
services:
  apiserver:
    container_name: api_container
    image: "refinement-voting-api:c6.0-001"
    env_file:
      - ./docker-env-vars-for-api
    networks:
      - backend_space

  webserver:
    container_name: webserver_container
    image: "refinement-voting-webserver:1.0"
    volumes:
      - ./nginx.without.tls.conf:/etc/nginx/conf.d/default.conf
      - ./ui.conf.json:/usr/share/nginx/html/ui-config.json
    ports:
      - "5000:80"
    networks: 
      - backend_space

networks:
  backend_space:
    name: backend_network
    driver: bridge